# Generated by Django 4.2 on 2023-09-30 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acknowledgement',
            old_name='vendor',
            new_name='owner',
        ),
    ]
